version: "3.8"
services:
  api:
    build: .
    ports:
      - "3000:3000"
    environment:
      - MONGO_URI=mongodb://db:27017/shortener
      - BASE_URL=http://localhost:3000
    depends_on:
      - db

  db:
    image: mongo:6
    container_name: url-shortener-db
    ports:
      - "27017:27017"

